#!/usr/bin/env python3
"""Download Sportmonks Football API v3 docs into a single local Markdown file."""

from __future__ import annotations

import re
import sys
import time
import urllib.error
import urllib.request
from datetime import datetime, timezone
from pathlib import Path

INDEX_URL = "https://docs.sportmonks.com/llms.txt"
FOOTBALL_SECTION = "Football API 3.0"
EXCLUDED_PATH_SEGMENTS = (
    "/motorsport-api/",
    "/odds-api/",
    "/core-api/",
    "/football-widgets/",
    "/beta-documentation/",
)

REQUEST_TIMEOUT = 30
REQUEST_DELAY_SECONDS = 0.4
MAX_RETRIES = 3
RETRY_BACKOFF_SECONDS = 2.0
USER_AGENT = "ModelloPrevisionaleCalcistico/1.0 (docs-fetcher)"

URL_PATTERN = re.compile(r"https://docs\.sportmonks\.com/v3/[^\s\)]+\.md")
LINK_PATTERN = re.compile(r"\[[^\]]*\]\((https://docs\.sportmonks\.com/v3/[^\)]+?\.md)\)")

PAGE_SEPARATOR = (
    "\n\n---\n\n"
    "<!-- Page separator -->\n\n"
    "---\n\n"
)


class HttpClient:
    """Minimal HTTP client using urllib (reliable SSL on Windows Store Python)."""

    def __init__(self, user_agent: str = USER_AGENT) -> None:
        self.headers = {
            "User-Agent": user_agent,
            "Accept": "text/markdown,text/plain,*/*",
        }

    def get_text(self, url: str) -> str:
        last_error: Exception | None = None

        for attempt in range(1, MAX_RETRIES + 1):
            try:
                request = urllib.request.Request(url, headers=self.headers)
                with urllib.request.urlopen(request, timeout=REQUEST_TIMEOUT) as response:
                    raw = response.read()
                    charset = response.headers.get_content_charset() or "utf-8"
                    return raw.decode(charset, errors="replace")
            except (urllib.error.URLError, TimeoutError) as exc:
                last_error = exc
                if attempt < MAX_RETRIES:
                    time.sleep(RETRY_BACKOFF_SECONDS * attempt)

        raise RuntimeError(f"Failed to fetch {url}") from last_error


def project_root() -> Path:
    return Path(__file__).resolve().parent.parent


def is_football_v3_url(url: str) -> bool:
    if "/v3/" not in url or not url.endswith(".md"):
        return False
    return not any(segment in url for segment in EXCLUDED_PATH_SEGMENTS)


def extract_urls_from_section(index_text: str) -> list[str]:
    """Extract unique Football API v3 markdown URLs preserving index order."""
    in_football_section = False
    seen: set[str] = set()
    urls: list[str] = []

    for line in index_text.splitlines():
        stripped = line.strip()
        if stripped.startswith("## "):
            title = stripped[3:].strip()
            in_football_section = title == FOOTBALL_SECTION
            continue

        if not in_football_section:
            continue

        for match in LINK_PATTERN.finditer(line):
            url = match.group(1)
            if is_football_v3_url(url) and url not in seen:
                seen.add(url)
                urls.append(url)

        for url in URL_PATTERN.findall(line):
            if is_football_v3_url(url) and url not in seen:
                seen.add(url)
                urls.append(url)

    return urls


def build_header(url_count: int) -> str:
    generated_at = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
    return (
        "# Sportmonks Football API v3 — Local Documentation Bundle\n\n"
        f"> Generated at: {generated_at}\n"
        f"> Source index: {INDEX_URL}\n"
        f"> Pages included: {url_count}\n\n"
        "This file is auto-generated by `scripts/fetch_sportmonks_docs.py`.\n"
        "Do not edit manually; re-run the script to refresh the content.\n"
    )


def write_index(docs_dir: Path, index_text: str) -> Path:
    index_path = docs_dir / "sportmonks-llms-index.md"
    header = (
        "# Sportmonks llms.txt Index\n\n"
        f"> Source: {INDEX_URL}\n"
        f"> Saved at: {datetime.now(timezone.utc).strftime('%Y-%m-%d %H:%M:%S UTC')}\n\n"
    )
    index_path.write_text(header + index_text, encoding="utf-8")
    return index_path


def write_bundle(
    docs_dir: Path,
    urls: list[str],
    client: HttpClient,
) -> tuple[Path, list[str], list[tuple[str, str]]]:
    bundle_path = docs_dir / "sportmonks-football-v3-docs.md"
    parts: list[str] = [build_header(len(urls))]
    failures: list[tuple[str, str]] = []

    for index, url in enumerate(urls, start=1):
        print(f"[{index}/{len(urls)}] Fetching {url}")
        try:
            content = client.get_text(url).strip()
            parts.append(f"<!-- Source: {url} -->\n\n{content}")
        except RuntimeError as exc:
            message = str(exc)
            failures.append((url, message))
            print(f"  ! Skipped: {message}", file=sys.stderr)
            parts.append(
                f"<!-- Source: {url} -->\n\n"
                f"<!-- Fetch failed: {message} -->\n"
            )

        if index < len(urls):
            parts.append(PAGE_SEPARATOR.strip("\n"))

        time.sleep(REQUEST_DELAY_SECONDS)

    bundle_path.write_text("\n".join(parts) + "\n", encoding="utf-8")
    return bundle_path, urls, failures


def main() -> int:
    root = project_root()
    docs_dir = root / "docs"
    docs_dir.mkdir(parents=True, exist_ok=True)

    client = HttpClient()

    print(f"Downloading index from {INDEX_URL}")
    index_text = client.get_text(INDEX_URL)
    index_path = write_index(docs_dir, index_text)
    print(f"Saved index to {index_path}")

    urls = extract_urls_from_section(index_text)
    if not urls:
        print("No Football API v3 markdown URLs found in index.", file=sys.stderr)
        return 1

    print(f"Found {len(urls)} Football API v3 pages to download")
    bundle_path, downloaded_urls, failures = write_bundle(docs_dir, urls, client)

    print()
    print("Done.")
    print(f"  Bundle: {bundle_path}")
    print(f"  Pages attempted: {len(downloaded_urls)}")
    print(f"  Failures: {len(failures)}")

    if failures:
        print("\nFailed URLs:", file=sys.stderr)
        for url, error in failures:
            print(f"  - {url}: {error}", file=sys.stderr)
        return 1

    return 0


if __name__ == "__main__":
    raise SystemExit(main())
